const express = require('express')
const userSignUpController = require('../controller/userSignUp')
const userSignInController = require('../controller/userSignIn')
const authenticationToken = require('../middleware/authentication')
const userDetailController = require('../controller/userDetail')
const logoutUserControllser = require('../controller/logoutUser')
const {emailCodeSendingController, emailCodeValidationController} = require("../controller/emailCodeValidation")
const resetPasswordController = require('../controller/resetPassword')
const updateUserBasicDetailsController = require('../controller/updateUserDetails')
const paymentOptionUpdateController = require('../controller/paymentOptionUpdate')
const shippingAddressUpdateController = require('../controller/shippingAddressUpdate')
const updatePasswordController = require("../controller/updatePassword")
const becomeSellerController = require('../controller/becomeASeller')
const deleteUserController = require('../controller/deleteAccount')
const router = express.Router()

router.post('/signup', userSignUpController)
router.post('/login', userSignInController)
router.get('/userDetails',authenticationToken, userDetailController)
router.get('/logout', logoutUserControllser)
router.post('/emailcode', emailCodeSendingController)
router.post('/validatecode',emailCodeValidationController)
router.post('/resetPassword', resetPasswordController)
router.put('/updateUserDetails',authenticationToken, updateUserBasicDetailsController)
router.put('/paymentOptionUpdate', paymentOptionUpdateController)
router.put('/shippingAddressUpdate', shippingAddressUpdateController)
router.put('/updatePassword', updatePasswordController)
router.put('/becomeSeller', becomeSellerController)
router.delete('/deleteUser', deleteUserController)

module.exports = router